name: update-page

on: 
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
      - run: pnpm install
      - run: pnpm run build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
      
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
