name: update-page

on: 
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
      - run: pnpm install
      - run: pnpm run build
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/dist
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
